name = "QuantLib"
uuid = "641dae7e-b2eb-11e8-36b1-0d425f221c6d"
authors = ["Matias Borghi <borghi.matias@gmail.com>"]
version = "0.1.0"

[deps]
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
